In [0]:
print("learntospark")

learntospark

<img src='files/learnspark_img/learn.JPG' width='280' height='200'>        <img src='files/learnspark_img/spark.png' width='300' height='280'>


=======================================================================================
<H2><center>How to Add Leading Zeros to a column in Spark DataFrame ? </center></H2>
###>>>>>>>>>>>>        Using PySpark         <<<<<<<<<<<<

=======================================================================================

<img src='files/learnspark_img/inp.JPG'> =========> <img src='files/learnspark_img/out.JPG'>

=======================================================================================

In [0]:
list_data=[["Babu",20],["Raja",8],["Mani",75],["Kalam",100],["Zoin",7],["Kal",53]]
df1=spark.createDataFrame(list_data,["name","score"])
df1.show()

+-----+-----+
| name|score|
+-----+-----+
| Babu|   20|
| Raja|    8|
| Mani|   75|
|Kalam|  100|
| Zoin|    7|
|  Kal|   53|
+-----+-----+

In [0]:
from pyspark.sql.functions import lpad
df2=df1.withColumn("score_000",lpad("score",3,"0"))

df2.display()

name,score,score_000
Babu,20,020
Raja,8,008
Mani,75,075
Kalam,100,100
Zoin,7,007
Kal,53,053

In [0]:
from pyspark.sql.functions import format_string
df2=df1.withColumn("score_000",format_string("%03d","score"))

df2.display()

#df1.withColumn("score_000",format_string("%s#%03d","name","score")).display()

name,score,score_000
Babu,20,Babu#020
Raja,8,Raja#008
Mani,75,Mani#075
Kalam,100,Kalam#100
Zoin,7,Zoin#007
Kal,53,Kal#053

In [0]:
from pyspark.sql.functions import concat,substring,lit
df2=df1.withColumn("score_000",concat(lit("00"),"score"))
df3=df2.withColumn("score_000",substring("score_000",-3,3))
df3.display()

#df1.withColumn("score_000",substring(concat(lit("00"),"score"),-3,3)).display()

name,score,score_000
Babu,20,020
Raja,8,008
Mani,75,075
Kalam,100,100
Zoin,7,007
Kal,53,053